### ISSUE TITLE
Update urllib?

### ISSUE THREAD

**Issue by thomasthebaker** [spgi-ci/spgci-python#8]
Are you able to update urllib3, it's been pinned to an older version which causes conflicts with other libraries in my projects. I'm sure this will affect others.  

Was there a reason to pin urllib3 it to 1.26.15? It would be good to upgrade it to >=2.1.0  and support the major v2 release.

https://github.com/spgi-ci/spgci-python/blob/ae94ce67e7890eb0c9c2e1c18ac0e1aa5808d324/pyproject.toml#L19

I've tested locally with the EWindowMarketData and it is fine with urllib3 == 2.2.2.

**Comment by achristie** [comment]
hi @thomasthebaker  - as of version 0.0.40 we pinned to `^1.26.15` so that it can at least take minor versions in the 1.x.x branch. Initially, there were a few issues with 2.0.0 and the requests library so we had pinned it. I'll revisit this next week.
